// Code generated by generateAST; DO NOT EDIT.
package ast

import (
	"github.com/mz1290/golox/internal/pkg/token"
)

type Stmt interface {
	StmtAcceptor
}

type StmtVisitor interface {
	VisitBlockStmt(stmt Block) (interface{}, error)
	VisitExpressionStmt(stmt Expression) (interface{}, error)
	VisitIfStmt(stmt If) (interface{}, error)
	VisitPrintStmt(stmt Print) (interface{}, error)
	VisitVarStmt(stmt Var) (interface{}, error)
}

type StmtAcceptor interface {
	Accept(v StmtVisitor) (interface{}, error)
}

type Block struct {
	Statements []Stmt
}

func (x Block) Accept(v StmtVisitor) (interface{}, error) {
	return v.VisitBlockStmt(x)
}

type Expression struct {
	Expression Expr
}

func (x Expression) Accept(v StmtVisitor) (interface{}, error) {
	return v.VisitExpressionStmt(x)
}

type If struct {
	Condition Expr
	ThenBranch Stmt
	ElseBranch Stmt
}

func (x If) Accept(v StmtVisitor) (interface{}, error) {
	return v.VisitIfStmt(x)
}

type Print struct {
	Expression Expr
}

func (x Print) Accept(v StmtVisitor) (interface{}, error) {
	return v.VisitPrintStmt(x)
}

type Var struct {
	Name *token.Token
	Initializer Expr
}

func (x Var) Accept(v StmtVisitor) (interface{}, error) {
	return v.VisitVarStmt(x)
}

